version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/:ro
    env_file:
      - ./.env

  
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db


  frontend:
    build: 
      context: ./frontend
    
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend


volumes:
  postgres_data:
