# Generated by Django 4.0.6 on 2022-09-12 11:00

import Tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timings', Tracker.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=200), blank=True, default=list, size=None)),
                ('strength', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
